version: "3.9"

services:
  voxcpm-api:
    image: voxcpm-openai-api:latest
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      VOXCPM_MODEL_ID: openbmb/VoxCPM-0.5B
      HF_HOME: /models
      TRANSFORMERS_CACHE: /models/transformers
      NVIDIA_VISIBLE_DEVICES: all
    volumes:
      - ./models:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
